### ISSUE TITLE
Update 1.15.5 - Classic Era 20th Anniversary

### ISSUE THREAD

**Issue by maximus210793** [GovtGeek/TinyTooltip-Wrath#13]
Hi,
can you update to the latest Classic Era 20th Anniversary Version 1.15.5.
Would be awesome.
Thanks a lot!

**Comment by GovtGeek** [comment]
I updated the repository, but I can't create a release via mobile. I may be able to get to it on Sunday.

**Comment by GovtGeek** [comment]
New version released with Classic Era version updated.
