### ISSUE TITLE
WoW Classic Era Update [Version 1.14.4]

### ISSUE THREAD

**Issue by maximus210793** [GovtGeek/TinyTooltip-Wrath#4]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game Version of 1.14.4?
Would be awesome, thanks a lot in advance!

**Comment by GovtGeek** [comment]
Thanks. I didn't write the original. I just try to keep this version working. I haven't tested in Classic Era, but I posted a change you can try out in the releases. Look for v3.4.3.2.

**Comment by maximus210793** [comment]
Could you release it also as a official Classic Era Version since the Wrath Version is working for Classic Era :)

**Comment by GovtGeek** [comment]
It should be updated on curse. It didn't like my release change so I had to do it by hand.
